# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::blobtk=0.6.5
