# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "BLOBTOOLKIT_GENERATEPARAMSFILE"
description: Generate a params file in json format for sanger-tol/blobtoolkit
keywords:
  - blobtoolkit/generateparamsfile
  - generateparamsfile
  - json
  - paramsfile
tools:
  - "blobtoolkit_generateparamsfile":
      description: "not a real tool!"
      homepage: "https://i.need.this.to.lint.org"
      documentation: "https://i.need.this.to.lint.org"
      tool_dev_url: "https://i.need.this.to.lint.org"
      doi: no DOI available
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - reference:
        type: file
        description: |
          Input assembly fasta file
        pattern: "[*.{fasta,fa,fna}]"
        ontologies:
          - edam: "http://edamontology.org/format_1929" # FASTA

  - blastp:
      type: file
      description: |
        The Uniprot Diamond Protein Database for BlastP (aligning proteins to a protein database)
      pattern: "*.dmnd"
      ontologies: []

  - blastn:
      type: directory
      description: |
        The NCBI Nucleotide database path for BlastN (aligning nucleotides to a nucleotide database)
      ontologies: []

  - blastx:
      type: file
      description: |
        The Uniprot Diamond Protein Database path for BlastX (aligning nucleotides to a protein database)
      pattern: "*.dmnd"
      ontologies: []

  - tax_dump:
      type: directory
      description: |
        Directory of the NCBI tax dump database
      ontologies: []

  - busco_lineages:
      type: string
      description: |
        CSV list of odb's to run in blobtoolkit
      ontologies: []

  - taxon:
      type: integer
      description: |
        Target organisms taxid
      pattern: "[0-9].*"
      ontologies: []

  - btk_extra_opts:
      type: map
      description: |
        Map of extra arguments for blobtoolkit
      ontologies: []

output:
  json_params_file:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "${prefix}.blobtoolkit_params_file.json":
          type: file
          description: CSV samplesheet required for Blobtoolkit
          ontologies:
            - edam: "http://edamontology.org/format_3464" # JSON
  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@mahesh-panchal"
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
