# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/modules/meta-schema.json
name: "cramalign_bwamem2alignhic"
description: |
  Aligns a subset of Hi-C reads from a CRAM file to a reference genome using bwa-mem2,
  pipes the resulting alignments through samtools fixmate and samtools sort, outputting
  an alignment in BAM format.
keywords:
  - sort
  - alignment
  - genomics
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
  - bwa:
      description: |
        BWA-mem2 is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: https://github.com/bwa-mem2/bwa-mem2
      documentation: http://www.htslib.org/doc/samtools.html
      arxiv: arXiv:1303.3997
      licence: ["MIT"]
      identifier: "biotools:bwa-mem2"
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - cram:
        type: file
        description: CRAM file containing Hi-C sequences to align
        pattern: "*.cram"
        ontologies:
          - edam: "http://edamontology.org/format_3462" # CRAM
    - crai:
        type: file
        description: CRAM index file
        pattern: "*.crai"
        ontologies:
          - edam: "http://edamontology.org/format_3475" # TSV
    - rglines:
        type: list
        description: A list of strings, each a valid SAM-format @RG header line,
          to pass to the aligner
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - index:
        type: file
        description: bwa-mem2 index of the reference to be aligned to
        ontologies: []
    - reference:
        type: file
        description: FASTA file containing reference for alignment
        pattern: "*.fasta(.gz)?"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
  - - chunkn:
        type: integer
        description: Integer index of CRAM chunk to map
    - range:
        type: list
        description: Start and end indices defining CRAM slices to align
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bam":
          type: file
          description: BAM file of mapped Hi-C sequences
          pattern: "*.bam"
          ontologies:
            - edam: "http://edamontology.org/format_2572" # BAM
  versions_bwamem2:
    - - ${task.process}:
          type: string
          description: Name of the process
      - bwamem2:
          type: string
          description: The name of the tool
      - bwa-mem2 version 2>| grep -o -E "[0-9]+(\.[0-9]+)+":
          type: eval
          description: The expression to obtain the version of the tool

  versions_samtools:
    - - ${task.process}:
          type: string
          description: Name of the process
      - samtools:
          type: string
          description: Name of the tool
      - samtools --version | head -1 | sed -e "s/samtools //":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: Name of the process
      - bwamem2:
          type: string
          description: The name of the tool
      - bwa-mem2 version 2>| grep -o -E "[0-9]+(\.[0-9]+)+":
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: Name of the process
      - samtools:
          type: string
          description: Name of the tool
      - samtools --version | head -1 | sed -e "s/samtools //":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@yumisims"
  - "@prototaxites"
maintainers:
  - "@prototaxites"
