name: "findtelomere"
description: |
  Run the core steps of the sanger-tol/telomere toolkit.
keywords:
  - telomere
  - findtelomere
  - windows
  - motif
tools:
  - find_telomere:
      description: |
        Scan the assembly for a telomeric repeat motif (default TTAGGG) on both strands.
      homepage: https://github.com/sanger-tol/telomere
      documentation: https://github.com/sanger-tol/telomere
      licence:
        - "BSD-3-Clause"
      identifier: ""
  - FindTelomereWindows:
      description: |
        Slide windows along scaffolds and flag regions where telomeric hits exceed a density threshold.
      homepage: https://github.com/sanger-tol/telomere
      documentation: https://github.com/sanger-tol/telomere
      licence:
        - "BSD-3-Clause"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - reference:
        type: file
        description: Assembly for telomere.
        pattern: "*.{fa,fna,fasta}"
    - telomereseq:
        type: string
        description: DNA sequence of a telomere motif
  - split_windows:
      type: boolean
      description: Run FindTelomereWindows in split mode
output:
  telomere:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.telomere":
          type: file
          description: Motif-hit intervals
          pattern: "*.telomere"
  telomere_bed_fwd:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.fwd.telomere.bed":
          type: file
          description: Forward telomeric intervals
          pattern: "*.fwd.telomere.bed"
  telomere_bed_rev:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.rev.telomere.bed":
          type: file
          description: Reverse telomeric intervals
          pattern: "*.rev.telomere.bed"
  windows:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.windows":
          type: file
          description: Telomere density windows
          pattern: "*.windows"
  windows_fwd:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.fwd.windows":
          type: file
          description: Forward windows
          pattern: "*.fwd.windows"
  windows_rev:
    - - meta:
          type: map
          description: Groovy Map containing sample information
      - "*.rev.windows":
          type: file
          description: Reverse windows
          pattern: "*.rev.windows"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@yumisims"
maintainers:
  - "@yumisims"
