# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "telomere_windows"
description: |
  Identify windows of the telomere file which maybe true telomeric sites
keywords:
  - telomere
  - windows
  - tsv

tools:
  - telomere.jar:
      description: |
        Script to identify likely telomeric sites.
      homepage: https://github.com/VGP/vgp-assembly/
      documentation: https://github.com/VGP/vgp-assembly/
      licence: ["GPL v2.0"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - telomere:
        type: file
        description: |
          TSV of putative telomeric sites
        pattern: "*.telomere"
        ontologies:
          - edam: "http://edamontology.org/format_3475" # TSV

output:
  windows:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.windows":
          type: file
          description: |
            TSV of likely telomeric sites
          ontologies:
            - edam: "http://edamontology.org/format_3475" # TSV
  versions_telomerewindows:
    - - ${task.process}:
          type: string
          description: The name of the process
      - telomere_windows:
          type: string
          description: The name of the module
      - 1.0.0:
          type: string
          description: The version of the module

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - telomere_windows:
          type: string
          description: The name of the module
      - 1.0.0:
          type: string
          description: The version of the module
authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
