site_name: "sanger-tol/nf-core-modules"
site_description: "An nf-core modules repository hosting Nextflow DSL2 modules for the Sanger Tree of Life organization."
site_url: "https://sanger-tol.github.io/nf-core-modules"
repo_url: "https://github.com/sanger-tol/nf-core-modules"
repo_name: "sanger-tol/nf-core-modules"

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home:
      - Overview: ./index.md
      - License: ./license.md

theme:
  name: material
  icon:
    logo: material/currency-sign
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: purple
      accent: blue-grey
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blurple
      accent: blue-grey
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
  - admonition
  - callouts
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: "¤"
