# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/subworkflows/yaml-schema.json
name: "pacbio_preprocess"
description: "Preprocesses PacBio sequencing data by demultiplexing with LIMA and marking duplicates (ULI data), adapter trimming (optional), and converting to FASTA/FASTQ/CRAM format."
keywords:
  - pacbio
  - demultiplex
  - adapter-trimming
  - duplicate-marking
components:
  - blast/blastn
  - blast/makeblastdb:
      git_remote: https://github.com/nf-core/modules.git
  - hifitrimmer/processblast:
      git_remote: https://github.com/nf-core/modules.git
  - hifitrimmer/filterbam:
      git_remote: https://github.com/nf-core/modules.git
  - lima:
      git_remote: https://github.com/nf-core/modules.git
  - pbmarkdup:
      git_remote: https://github.com/nf-core/modules.git

input:
  - ch_reads:
      type: file
      description: |
        Input channel containing sequencing reads in BAM, FASTQ, or FASTA format.
        Structure: [ val(meta), path(reads) ]
      pattern: "*.(bam|fastq|fq|fasta|fa|fna)(.gz)?"
  - ch_adapter_yaml:
      type: file
      description: |
        Input channel containing YAML file for HiFiTrimmer adapter trimming, specific to each read files, paired by meta information.
        Structure: [ val(meta), path(yaml) ]
      pattern: "*.yaml"
  - val_adapter_fasta:
      type: file
      description: |
        Adapter database for BLASTN adapter detection.
      pattern: "*.(fasta|fa|fna)"
  - val_uli_primers:
      type: file
      description: |
        ULI primer FASTA file used by LIMA for barcode demultiplexing.
        Provide a primer FASTA to enable demultiplexing, or an empty channel to skip.
      pattern: "*.fasta|*.fa"
  - val_pbmarkdup:
      type: boolean
      description: |
        Whether to run pbmarkdup for duplicate marking.

output:
  - untrimmed_fastx:
      type: file
      description: |
        Channel containing preprocessed reads that are not filtered/trimmed with hifitrimmer in FASTA/FASTQ format.
        Structure: [ val(meta), path(fasta/fastq) ]
      pattern: "*.fasta|*.fa|*.fastq|*.fq"
  - trimmed_fastx:
      type: file
      description: |
        Channel containing preprocessed reads that have been filtered/trimmed with hifitrimmer in FASTA/FASTQ format.
        Structure: [ val(meta), path(fasta/fastq) ]
      pattern: "*.fasta|*.fa|*.fastq|*.fq"
  - untrimmed_bam:
      type: file
      description: |
        Channel containing preprocessed reads that are not filtered/trimmed with hifitrimmer in BAM format.
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - lima_report:
      type: file
      description: |
        LIMA demultiplexing reports (if val_uli_primers).
        Structure: [ val(meta), path(report) ]
      pattern: "*.report.csv"
  - lima_summary:
      type: file
      description: |
        LIMA demultiplexing summary (if uli_primers).
        Structure: [ val(meta), path(summary) ]
      pattern: "*.summary.txt"
  - hifitrimmer_bed:
      type: file
      description: |
        HiFiTrimmer adapter trim coordinates in BED format (if val_adapter_fasta and ch_adapter_yaml provided).
        Structure: [ val(meta), path(bed) ]
      pattern: "*.bed"
  - hifitrimmer_summary:
      type: file
      description: |
        HiFiTrimmer trimming summary (if val_adapter_fasta and ch_adapter_yaml provided).
        Structure: [ val(meta), path(summary) ]
      pattern: "*.summary.json"
  - pbmarkdup_stats:
      type: file
      description: |
        pbmarkdup duplicate marking statistics (if val_uli_primers provided).
        Structure: [ val(meta), path(log) ]
      pattern: "*.log"
  - versions:
      type: file
      description: |
        File containing software versions.
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@sainsachiko"
maintainers:
  - "@sainsachiko"
