# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/refs/heads/main/subworkflows/yaml-schema.json
name: "pacbio_preprocess"
description: "Preprocesses PacBio sequencing data by demultiplexing with LIMA and marking duplicates (ULI data), adapter trimming (optional), and converting to FASTA/FASTQ/CRAM format."
keywords:
  - pacbio
  - demultiplex
  - adapter-trimming
  - duplicate-marking
components:
  - blast/blastn:
      git_remote: https://github.com/nf-core/modules.git
  - hifitrimmer/processblast:
      git_remote: https://github.com/nf-core/modules.git
  - hifitrimmer/filterbam:
      git_remote: https://github.com/nf-core/modules.git
  - lima:
      git_remote: https://github.com/nf-core/modules.git
  - pbmarkdup:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/fasta:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/fastq:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/import:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/view:
      git_remote: https://github.com/nf-core/modules.git
  - seqkit/fq2fa:
      git_remote: https://github.com/nf-core/modules.git
  - tabix/bgzip:
      git_remote: https://github.com/nf-core/modules.git

input:
  - ch_reads:
      type: file
      description: |
        Input channel containing sequencing reads in CRAM, BAM, FASTQ, or FASTA format.
        Structure: [ val(meta), path(reads) ]
      pattern: "*.(cram|bam|fastq|fq|fasta|fa|fna)(.gz)?"
  - ch_adapter_yaml:
      type: file
      description: |
        Input channel containing YAML file for HiFiTrimmer adapter trimming.
        Structure: [ val(meta), path(yaml) ]
      pattern: "*.yaml"
  - adapter_db:
      type: file
      description: |
        Adapter database for BLASTN adapter detection.
      pattern: "*"
  - uli_primers:
      type: boolean
      description: Whether to run LIMA for ULI barcode demultiplexing

output:
  - fastx:
      type: file
      description: |
        Channel containing preprocessed reads in FASTA/FASTQ format.
        Structure: [ val(meta), path(fasta/fastq) ]
      pattern: "*.fasta|*.fa|*.fastq|*.fq"
  - lima_reports:
      type: file
      description: |
        LIMA demultiplexing reports (if uli_primers).
        Structure: [ val(meta), path(report) ]
      pattern: "*.report.csv"
  - lima_summary:
      type: file
      description: |
        LIMA demultiplexing summary (if uli_primers).
        Structure: [ val(meta), path(summary) ]
      pattern: "*.summary.txt"
  - hifitrimmer_bed:
      type: file
      description: |
        HiFiTrimmer adapter trim coordinates in BED format (if adapter_db and ch_adapter_yaml provided).
        Structure: [ val(meta), path(bed) ]
      pattern: "*.bed"
  - hifitrimmer_summary:
      type: file
      description: |
        HiFiTrimmer trimming summary (if adapter_db and ch_adapter_yaml provided).
        Structure: [ val(meta), path(summary) ]
      pattern: "*.summary.json"
  - pbmarkdup_stats:
      type: file
      description: |
        pbmarkdup duplicate marking statistics (if uli_primers).
        Structure: [ val(meta), path(log) ]
      pattern: "*.log"
  - versions:
      type: file
      description: |
        File containing software versions.
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@sainsachiko"
maintainers:
  - "@sainsachiko"
