# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/refs/heads/main/subworkflows/yaml-schema.json
name: "cram_map_long_reads"
description: "Maps PacBio/ONT reads in unaligned CRAMs format to a set of references. Also includes optional preprocessing for PacBio reads using the pacbio_preprocess subworkflow."
keywords:
  - longread
  - pacbio
  - ont
  - align
  - bam
components:
  - cramalign/gencramchunks
  - cramalign/minimap2align
  - bam_samtools_merge_markdup
  - pacbio_preprocess
  - samtools/index:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/splitheader:
      git_remote: https://github.com/nf-core/modules.git
  - minimap2/index:
      git_remote: https://github.com/nf-core/modules.git

input:
  - ch_assemblies:
      type: file
      description: |
        Input channel containing assemblies to align PacBio/ONT reads to
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.fn?a(sta)?(.gz)?"
  - ch_crams:
      type: file
      description: |
        Input channel containing PacBio/ONT CRAM files for mapping.
        Structure: [ val(meta), path(cram) ] or [ val(meta), [ path(cram1), path(cram2), ... ] ]
      pattern: "*.cram"
  - val_cram_chunk_size:
      type: integer
      description: Size of chunk to split CRAM files into
  - ch_hifitrimmer_adapter_yaml:
      type: file
      description: |
        Input channel containing YAML file for HiFiTrimmer adapter trimming.
        Structure: [ val(meta), path(yaml) ]
      pattern: "*.yaml"
  - pacbio_adapter_db:
      type: file
      description: |
        Adapter database for BLASTN adapter detection.
      pattern: "*.tar.gz"
  - pacbio_uli_primers:
      type: file
      description: |
        ULI primer FASTA file used by LIMA for barcode demultiplexing.
        Provide a primer FASTA to enable demultiplexing, or an empty channel to skip.
      pattern: "*.fasta|*.fa"
output:
  - bam:
      type: file
      description: |
        Channel containing the BAM files describing long-read alignments to the input assemblies
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - pacbio_lima_reports:
      type: file
      description: |
        LIMA demultiplexing reports (if uli_primers).
        Structure: [ val(meta), path(report) ]
      pattern: "*.report.csv"
  - pacbio_lima_summary:
      type: file
      description: |
        LIMA demultiplexing summary (if uli_primers).
        Structure: [ val(meta), path(summary) ]
      pattern: "*.summary.txt"
  - pacbio_hifitrimmer_bed:
      type: file
      description: |
        HiFiTrimmer adapter trim coordinates in BED format (if adapter_db and ch_adapter_yaml provided).
        Structure: [ val(meta), path(bed) ]
      pattern: "*.bed"
  - pacbio_hifitrimmer_summary:
      type: file
      description: |
        HiFiTrimmer trimming summary (if adapter_db and ch_adapter_yaml provided).
        Structure: [ val(meta), path(summary) ]
      pattern: "*.summary.json"
  - pacbio_pbmarkdup_stats:
      type: file
      description: |
        pbmarkdup duplicate marking statistics (if uli_primers).
        Structure: [ val(meta), path(log) ]
      pattern: "*.log"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@prototaxites"
  - "@sainsachiko"
maintainers:
  - "@sainsachiko"
