# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hifi_trimmer"
description: |
  Run hifi_trimmer to filter and trim adapter hits from PacBio HiFi reads using BLAST against
  adapter sequences. Primary output is a BED describing regions to exclude; filtered FASTA/FASTQ,
  an optional hits file and a JSON summary are also produced.
keywords:
  - pacbio
  - hifi_trimmer
  - trimming
tools:
  - hifi_trimmer:
      description: |
        hifi_trimmer: tools for processing HiFi read BLAST results and filtering/trimming
        BAM files to output processed FASTA/FASTQ and accompanying summary and hit (optional) files.
      homepage: "https://github.com/sanger-tol/hifi-trimmer"
      documentation: "https://github.com/sanger-tol/hifi-trimmer"
      licence: ["MIT"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: Input BAM file to filter
        pattern: "*.bam"
    - blast:
        type: file
        description: BLAST output file used by hifi_trimmer (e.g. .blast, .out)
        pattern: "*.blast"
  - yaml:
      type: file
      description: YAML configuration file for `hifi_trimmer` (may contain barcodes)
      pattern: "*.{yaml,yml}"
  - - meta1:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - barcode:
        type: string
        description: Optional barcode string to substitute 'SAMPLEBARCODE' into the YAML; empty string if unused
output:
  filtered:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.hifi_trimmer.fast{q,a}.gz":
          type: file
          description: Gzipped FASTA/FASTQ produced by hifi_trimmer
          pattern: "*.hifi_trimmer.fast{q,a}.gz"
          ontologies:
            - edam: "http://edamontology.org/format_1930" # FASTQ
            - edam: "http://edamontology.org/format_1929" # FASTA
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bed.gz":
          type: file
          description: Gzipped BED file of selected reads
          pattern: "*.bed.gz"
          ontologies:
            - edam: "http://edamontology.org/format_3003" # BED
            - edam: http://edamontology.org/format_3989 # GZIP format
  summary:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.summary.json":
          type: file
          description: JSON summary produced by hifi_trimmer
          pattern: "*.summary.json"
          ontologies:
            - edam: "http://edamontology.org/format_3464" # JSON
  hits:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.hits":
          type: file
          description: Optional hits file produced by hifi_trimmer (may be absent when no hits found or '-hf' is not specified)
          pattern: "*.hits"
          ontologies: []
  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@sainsachiko"
maintainers:
  - "@sainsachiko"
