# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "telomere_extract"
description: |
  Extract telomeric sites from telomere file into bed and bedgraph outputs
keywords:
  - telomere
  - extract
  - awk
  - bed
  - bedgraph
tools:
  - gawk:
      description: "GNU awk"
      homepage: "https://www.gnu.org/software/gawk/"
      documentation: "https://www.gnu.org/software/gawk/manual/"
      tool_dev_url: "https://www.gnu.org/prep/ftp.html"
      licence: ["GPL v3"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - telomere:
        type: file
        description: |
          Telomere file containing telomeric sites.
        pattern: "*.telomere"
        ontologies: []

output:
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bed":
          type: file
          description: |
            Telomere file formatted to bed
          ontologies:
            - edam: "http://edamontology.org/format_3003" # BED

  bedgraph:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bedgraph":
          type: file
          description: |
            Telomere file formatted to bedgraph
          ontologies:
            - edam: "http://edamontology.org/format_3583" # BEDGRAPH
  versions_telomereextract:
    - - ${task.process}:
          type: string
          description: The name of the process
      - telomere_extract:
          type: string
          description: The name of the module
      - awk -Wversion | sed '1!d; s/.*Awk //; s/,.*//':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - telomere_extract:
          type: string
          description: The name of the module
      - awk -Wversion | sed '1!d; s/.*Awk //; s/,.*//':
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
