name: longranger_align
description: Performs alignment of Illumina 10X sequencing data to the indexed reference genome
keywords:
  - longranger
  - align
  - 10X
tools:
  - longranger:
      description: Long Ranger is a set of analysis pipelines that processes Chromium sequencing output to align reads and call and phase SNPs, indels, and structural variants.
      homepage: https://support.10xgenomics.com/genome-exome/software/pipelines/latest/what-is-long-ranger
      documentation: https://support.10xgenomics.com/genome-exome/software/pipelines/latest/what-is-long-ranger
      tool_dev_url: https://github.com/10XGenomics/longranger
      doi: no DOI available
      licence: ["https://support.10xgenomics.com/genome-exome/software/downloads/latest"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'pEimTen1' ]
    - reference:
        type: file
        description: Reference built by longranger/mkref
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'pEimTen1' ]
    - fastq:
        type: file
        description: Illumina 10X reads in fastq format
        pattern: "*.fq.gz"
output:
  bam:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'pEimTen1' ]
      - "${meta.id}/outs/possorted_bam.bam":
          type: file
          description: Sorted BAM file
          pattern: "${meta.id}/outs/possorted_bam.bam"
  bai:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'pEimTen1' ]
      - "${meta.id}/outs/possorted_bam.bam.bai":
          type: file
          description: Bam index
          pattern: "${meta.id}/outs/possorted_bam.bam.bai"
  csv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'pEimTen1' ]
      - "${meta.id}/outs/summary.csv":
        type: file
        description: Summary CSV file
        pattern: "${meta.id}/outs/summary.csv"
  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"
authors:
  - "@ksenia-krasheninnikova"
  - "@prototaxites"
