# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "samtools_grepreadgroups"
description: |
  Get the @RG lines from a BAM file as a string.
keywords:
  - bam
  - header
  - read group
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information. e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: sequence_trace file
        pattern: "*.{bam,sam,cram}"
        ontologies:
          - edam: http://edamontology.org/format_2572 # BAM
          - edam: http://edamontology.org/format_2573 # SAM
          - edam: http://edamontology.org/format_3462 # CRAM
output:
  read_group:
    - meta:
        type: map
        description: |
          Groovy Map containing sample information. e.g. `[ id:'sample1' ]`
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: versions.yml
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@prototaxites"
maintainers:
  - "@prototaxites"
