# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/refs/heads/main/subworkflows/yaml-schema.json
name: "gap_finder"
description: Generate a bed file containing gaps and their length
keywords:
  - gap
  - bed
  - adapters
  - trimming
  - fasta
components:
  - seqtk/cutn:
      git_remote: https://github.com/nf-core/modules.git
  - gawk:
      git_remote: https://github.com/nf-core/modules.git
  - gunzip:
      git_remote: https://github.com/nf-core/modules.git

input:
  - ch_reference:
      type: file
      description: |
        Structure [ val(meta), path(reference) ]
        Meta is the Groovy Map containing sample information
        Reference is the fasta for analysis
output:
  - gap_file:
      type: file
      description: |
        Structure: [ val(meta), path(gap_file) ]
        Bed file containing gap location and lengths
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
