# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/refs/heads/main/subworkflows/yaml-schema.json
name: "telo_finder"
description: Generate Telomere bedgraphs given a telomere motif
keywords:
  - telomere
  - bedgraph
  - windows
  - regions
  - fasta
components:
  - telomere/regions
  - telomere/windows
  - telomere/extract
  - gawk:
      git_remote: https://github.com/nf-core/modules.git

input:
  - ch_reference:
      type: file
      description: |
        Structure [ val(meta), path(reference) ]
        Meta is the Groovy Map containing sample information
        Reference is the fasta for analysis
  - ch_telomereseq:
      type: string
      description: |
        A string containing the DNA sequence of a telomere motif
  - val_split_telomere:
      type: boolean
      description: |
        A boolean to control use of the gawk to split the telomere.

output:
  - bedgraph_file:
      type: file
      description: |
        Structure: [ val(meta), [path(gap_file)] ]
        Collection of 1 or 3 telomere bed files.
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
