# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "kmercounter"
description: |
  A rust based tool based on Needletail's FASTA parser tallies k-mer counts
  for large sequencing rounds. Written with downstream processing with Tensorflow
  or numpy in mind.
keywords:
  - kmer
  - counts
  - npy
  - fasta
tools:
  - kmer-counter:
      description: |
        A rust based tool based on Needletail's FASTA parser tallies k-mer counts
        for large sequencing rounds. Written with downstream processing with Tensorflow
        or numpy in mind.
      homepage: https://github.com/CobiontID/kmer-counter
      documentation: https://github.com/CobiontID/kmer-counter
      license: ["MIT"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - fasta:
        type: file
        description: |
          Input fasta assembly file

    - kmer_size:
        type: integer
        description: |
          Size of kmer to scan the genome for.

output:
  npy:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - fasta:
          type: file
          description: |
            Input fasta assembly file
      - "*.npy":
          type: file
          description: |
            A Numpy file containing the kmer counts.

  versions:
    - "versions.yml":
        type: file
        description: File containing software versions
        pattern: "versions.yml"

authors:
  - "@DLBPointon"
maintainers:
  - "@DLBPointon"
