# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/refs/heads/main/subworkflows/yaml-schema.json
name: "longread_mapping"
description: "Maps PacBio/ONT reads in unaligned CRAMs format to a set of references."
keywords:
  - longread
  - pacbio
  - ont
  - align
  - bam
components:
  - cramalign/gencramchunks
  - cramalign/minimap2alignlongread
  - samtools/index:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/faidx:
      git_remote: https://github.com/nf-core/modules.git
  - samtools/merge:
      git_remote: https://github.com/nf-core/modules.git
  - minimap2/index:
      git_remote: https://github.com/nf-core/modules.git

input:
  - ch_assemblies:
      type: file
      description: |
        Input channel containing assemblies to align PacBio/ONT reads to
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.fn?a(sta)?(.gz)?"
  - ch_crams:
      type: file
      description: |
        Input channel containing PacBio/ONT CRAM files for mapping.
        Structure: [ val(meta), path(cram) ] or [ val(meta), [ path(cram1), path(cram2), ... ] ]
      pattern: "*.cram"
  - val_cram_chunk_size:
      type: integer
output:
  - bam:
      type: file
      description: |
        Channel containing the BAM files describing long-read alignments to the input assemblies
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@prototaxites"
  - "@sainsachiko"
maintainers:
  - "@sainsachiko"
