---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "hiccramalign_bwamem2align"
description: |
  Aligns a subset of Hi-C reads from a CRAM file to a reference genome using bwa-mem2,
  pipes the resulting alignments through samtools fixmate and samtools sort, outputting
  an alignment in BAM format.
keywords:
  - sort
  - example
  - genomics
tools:
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
  - bwa:
      description: |
        BWA-mem2 is a software package for mapping DNA sequences against
        a large reference genome, such as the human genome.
      homepage: https://github.com/bwa-mem2/bwa-mem2
      documentation: http://www.htslib.org/doc/samtools.html
      arxiv: arXiv:1303.3997
      licence: ["MIT"]
      identifier: "biotools:bwa-mem2"

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`

    - cram:
        type: file
        description: CRAM file containing Hi-C sequences to align
        pattern: "*.cram"
        ontologies:
          - edam: "http://edamontology.org/format_3462" # CRAM

    - crai:
        type: file
        description: CRAM index file
        pattern: "*.crai"
        ontologies:
          - edam: "http://edamontology.org/format_3475" # TSV

    - chunkn:
        type: integer
        description: Integer index of CRAM chunk to map

    - range:
        type: list
        description: Start and end indices defining CRAM slices to align

    - index:
        type: file
        description: bwa-mem2 index of the reference to be aligned to

    - reference:
        type: file
        description: FASTA file containing reference for alignment
        pattern: "*.fasta(.gz)?"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA

output:
  - bam:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bam":
          type: file
          description: BAM file of mapped Hi-C sequences
          pattern: "*.bam"
          ontologies:
            - edam: "http://edamontology.org/format_2572" # BAM

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@yumisims"
  - "@prototaxites"
maintainers:
  - "@prototaxites"
