# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "genomestatistics"
description: |
  Evaluate a number of standard metrics for a genome assembly, including
  basic statistics, MerquryFK for completeness/QV scores, and BUSCO

  To match a FastK database to an assembly, it assumes that
keywords:
  - assembly
  - qc
  - busco
  - merqury
components:
  - samtools/sort
  - samtools/index
input:
  - ch_bam:
      type: file
      description: |
        The input channel containing the BAM/CRAM/SAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.{bam/cram/sam}"
## TODO nf-core: List all of the channels used as output with a descriptions and their structure
output:
  - bam:
      type: file
      description: |
        Channel containing BAM files
        Structure: [ val(meta), path(bam) ]
      pattern: "*.bam"
  - bai:
      type: file
      description: |
        Channel containing indexed BAM (BAI) files
        Structure: [ val(meta), path(bai) ]
      pattern: "*.bai"
  - csi:
      type: file
      description: |
        Channel containing CSI files
        Structure: [ val(meta), path(csi) ]
      pattern: "*.csi"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@prototaxites"
maintainers:
  - "@prototaxites"
