# yaml-language-server: $schema=https://raw.githubusercontent.com/sanger-tol/nf-core-modules/main/modules/meta-schema.json
name: blast_blastn
description: Queries a BLAST DNA database from a FASTA/FASTQ/BAM file containing query sequences.
keywords:
  - fasta
  - fastq
  - bam
  - blast
  - blastn
  - DNA sequence
  - taxids
tools:
  - blast:
      description: |
        BLAST finds regions of similarity between biological sequences.
      homepage: https://blast.ncbi.nlm.nih.gov/Blast.cgi
      documentation: https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=Blastdocs
      doi: 10.1016/S0022-2836(05)80360-2
      licence: ["US-Government-Work"]
      identifier: ""
  - samtools:
      description: |
        SAMtools is a set of utilities for interacting with and post-processing
        short DNA sequence read alignments in the SAM, BAM and CRAM formats, written by Heng Li.
        These files are generated as output by short read aligners like BWA.
      homepage: http://www.htslib.org/
      documentation: http://www.htslib.org/doc/samtools.html
      doi: 10.1093/bioinformatics/btp352
      licence: ["MIT"]
      identifier: biotools:samtools
  - seqkit:
      description: "Cross-platform and ultrafast toolkit for FASTA/Q file manipulation,
        written by Wei Shen."
      homepage: "https://github.com/shenwei356/seqkit"
      documentation: "https://bioinf.shenwei.me/seqkit/"
      doi: "10.1371/journal.pone.0163962"
      licence: ["MIT"]
      identifier: biotools:seqkit

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - input:
        type: file
        description: Input FASTA/FASTQ/BAM file containing queries sequences
        pattern: "*.{fa,fasta,fa.gz,fasta.gz,bam,fastq,fq,fastq.gz,fq.gz}"
        ontologies: []
  - - meta2:
        type: map
        description: |
          Groovy Map containing db information
          e.g. [ id:'test2', single_end:false ]
    - db:
        type: directory
        description: Directory containing the blast database
        pattern: "*"
  - taxidlist:
      type: file
      description: File containing NCBI taxon ids, one per line, for filtering the database.
      pattern: "*.{txt}"
  - taxids:
      type: string
      description: Comma-delimited list of NCBI taxon ids for filtering the database.
      pattern: "^[0-9]+(,[0-9]+)*$"
  - negative_tax:
      type: boolean
      description: Use negative filtering (true) to exclude taxon ids or normal filtering (false).
      pattern: "true or false"
output:
  txtgz:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.txt.gz":
          type: file
          description: gzipped file containing blastn hits
          pattern: "*.txt.gz"
          ontologies: []
  versions_blast:
    - - ${task.process}:
          type: string
          description: Name of the process
      - blastn:
          type: string
          description: The name of the tool
      - 'blastn -version 2>&1 | sed "s/^.*blastn: //; s/ .*$//"':
          type: eval
          description: The expression to obtain the version of the tool

  versions_samtools:
    - - ${task.process}:
          type: string
          description: Name of the process
      - samtools:
          type: string
          description: Name of the tool
      - 'samtools --version | head -1 | sed -e "s/samtools //"':
          type: eval
          description: The expression to obtain the version of the tool

  versions_seqkit:
    - - ${task.process}:
          type: string
          description: Name of the process
      - seqkit:
          type: string
          description: The name of the tool
      - 'seqkit | sed "3!d; s/Version: //"':
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: Name of the process
      - blastn:
          type: string
          description: The name of the tool
      - 'blastn -version 2>&1 | sed "s/^.*blastn: //; s/ .*$//"':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: Name of the process
      - samtools:
          type: string
          description: Name of the tool
      - 'samtools --version | head -1 | sed -e "s/samtools //"':
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: Name of the process
      - seqkit:
          type: string
          description: The name of the tool
      - 'seqkit | sed "3!d; s/Version: //"':
          type: eval
          description: The expression to obtain the version of the tool

authors:
  - "@sainsachiko"
  - "@joseespinosa"
  - "@drpatelh"
maintainers:
  - "@sainsachiko"
