# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "contactbed"
description: |
  Converts BED file to contacts BED format using shell utilities.
keywords:
  - contacts
  - bed
  - hic
  - pairs
tools:
  - coreutils:
      description: |
        GNU coreutils provides standard utilities such as paste and tr used during conversion.
      homepage: https://www.gnu.org/software/coreutils/
      licence: ["GPL v3.0"]
  - awk:
      description: |
        AWK is used to transform BED records into the contacts format.
      homepage: https://gnu.org/software/gawk/
      licence: ["GPL v3.0"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - file:
        type: file
        description: |
          BED file to convert to contacts format.
        pattern: "*.bed"
        ontologies:
          - edam: http://edamontology.org/format_3003
output:
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bed":
          type: file
          description: |
            Contacts BED file generated from the input BED file.
          pattern: "*.bed"
          ontologies:
            - edam: http://edamontology.org/format_3003
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@sanger-tol"
maintainers:
  - "@sanger-tol"

