//
// MODULE IMPORT BLOCK
//
include { PRETEXT2ASM  } from '../../../modules/local/pretext2asm'
include { JUICERC         } from '../../../modules/local/juicerc'
include { MAKE_HEADER     } from '../../../modules/local/make_header'
include { MAKE_PAIRS      } from '../../../modules/local/make_pairs'
include { PRETEXTMAP      } from '../../../modules/nf-core/pretextmap/main'
workflow ZIPPYPRETEXT {

    take:
    ch_fasta // channel: fasta file to produce the mapped bam
    ch_agp // channel: agp file generated by PretextMap
    ch_hicmap // channel: alignment bin file or bam file of Hi-C reads
    ch_idxfile // channel: fasta index file to produce the mapped bam

    main:

    ch_zippy_inputs = ch_fasta
        .combine(ch_agp, by: 0)
        .combine(ch_hicmap, by: 0)
        .combine(ch_idxfile, by: 0)
        .multiMap { meta, fasta, agp, hicmap, idx ->
            fasta:   tuple(meta, fasta)
            agp:     tuple(meta, agp)
            hicmap:  tuple(meta, hicmap)
            idxfile: tuple(meta, idx)
        }

    ch_versions = channel.empty()

    //
    // MODULE: GENERATE CORRECT AGP FILE
    //
    PRETEXT2ASM (
        ch_zippy_inputs.fasta,
        ch_zippy_inputs.agp
    )
    ch_correctedagp = PRETEXT2ASM.out.correctedagp

    PRETEXT_TO_ASM.out.correctedagp.map{ agpid, agp -> agp}.set{agp}

    //
    // MODULE: GENERATE NEW ALIGNMENT FILE USING JUICERC
    //
    JUICERC (
        ch_zippy_inputs.hicmap,
        ch_zippy_inputs.agp,
        ch_zippy_inputs.idxfile
    )
    ch_alignment = JUICERC.out.alignment
    JUICERC.out.outlog
        .combine(ch_zippy_inputs.fasta, by: 0)
        .map { meta, outlog, _meta2, _fa ->
            tuple(meta, outlog)
        }
        .set { ch_outlog }

    //
    // MODULE: GENERATE HEADER
    //
    MAKE_HEADER (
        ch_outlog
    )
    MAKE_HEADER.out.header.map{ header_id, header -> header}.set{ch_header}

    //
    // MODULE: GENERATE PAIR FILE BY COMBINING HEADER AND NEW ALIGNMENT FILE
    //
    MAKE_PAIRS (
        ch_alignment,
        ch_header
    )
    ch_pairs = MAKE_PAIRS.out.pairs

    //
    // MODULE: GENERATE NEW PRETEXT FILE
    //
    PRETEXTMAP (
        ch_pairs,
        [[],[],[]]
    )
    ch_map = PRETEXTMAP.out.pretext

    emit:
    // TODO nf-core: edit emitted channels
    bam      = SAMTOOLS_SORT.out.bam           // channel: [ val(meta), [ bam ] ]
    bai      = SAMTOOLS_INDEX.out.bai          // channel: [ val(meta), [ bai ] ]
    csi      = SAMTOOLS_INDEX.out.csi          // channel: [ val(meta), [ csi ] ]
}
