# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "mask_softmask2bed"
description: |
  Find all soft-masked regions in a Fasta file and print their coordinates
  in BED format
keywords:
  - fasta
  - masking
  - coordinates
  - genomics
tools:
  - seqtk:
      description: Seqtk is a fast and lightweight tool for processing sequences in
        the FASTA or FASTQ format. The seqtk seq command enables common transformation
        operations on FASTA or FASTQ files.
      homepage: https://github.com/lh3/seqtk
      documentation: https://docs.csc.fi/apps/seqtk/
      tool_dev_url: https://github.com/lh3/seqtk
      licence:
        - "MIT"
      identifier: biotools:seqtk
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - fasta:
        type: file
        description: Soft-masked Fasta file
        pattern: "*.{fa,fasta}(.gz)?"
        ontologies:
          - edam: "http://edamontology.org/format_1929" # FASTA
output:
  bed:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.bed":
          type: file
          description: BED file of all soft-masked regions
          pattern: "*.bed"
          ontologies:
            - edam: "http://edamontology.org/format_3584" # bedstrict
  versions_softmask2bed:
    - - ${task.process}:
          type: string
          description: The name of the process
      - softmask2bed:
          type: string
          description: The name of the tool
      - echo 1.0:
          type: eval
          description: The expression to obtain the version of the tool
  versions_seqtk:
    - - ${task.process}:
          type: string
          description: The name of the process
      - seqtk:
          type: string
          description: The name of the tool
      - "seqtk 2>&1 | sed -n 's/^Version: //p'":
          type: eval
          description: The expression to obtain the version of the tool
topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - softmask2bed:
          type: string
          description: The name of the tool
      - echo 1.0:
          type: eval
          description: The expression to obtain the version of the tool
    - - ${task.process}:
          type: string
          description: The name of the process
      - seqtk:
          type: string
          description: The name of the tool
      - "seqtk 2>&1 | sed -n 's/^Version: //p'":
          type: eval
          description: The expression to obtain the version of the tool
authors:
  - "@muffato"
maintainers:
  - "@muffato"
